# Generated by Django 4.0.4 on 2022-05-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remember_text', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('remembers_photo', models.ImageField(upload_to='')),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
