# Generated by Django 4.0.4 on 2022-05-28 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remembers',
            old_name='remember_text',
            new_name='header',
        ),
        migrations.RenameField(
            model_name='remembers',
            old_name='remembers_photo',
            new_name='remember_photo',
        ),
    ]
