# Generated by Django 4.0 on 2022-06-27 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0002_remove_remembers_add_impress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_place', models.CharField(max_length=30, verbose_name='Название места')),
                ('comments', models.TextField(max_length=120, verbose_name='Комментарии')),
                ('img_impression', models.ImageField(upload_to='')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.DeleteModel(
            name='Remembers',
        ),
        migrations.CreateModel(
            name='AdvUser',
            fields=[
                ('impression_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.impression')),
                ('is_activated', models.BooleanField(db_index=True, default=True, verbose_name='Активировался?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            bases=('app.impression',),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
